name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Maven test
        run: mvn test

      - name: Maven Checkstyle
        run: mvn checkstyle:checkstyle  

      - name: Maven Build
        run: mvn install

      - name: massge step
        run: echo "This is a custom step"