name: Hprofile Actions
on: 
    - workflow_dispatch
    - push 

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      # 1. تثبيت Java 11 وتفعيل الكاش (يجب أن تكون أولاً)
      - name: Set Java 11 and Cache Maven
        uses: actions/setup-java@v3
        with:
         distribution: 'temurin'
         java-version: '11'

      # 2. دمج أوامر Maven (لتوليد كل التقارير مرة واحدة)
      - name: Build, Test, Checkstyle, and Coverage
        run: mvn clean verify checkstyle:checkstyle


      # 3. تثبيت Sonar Scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7
   
      - name: SonarQube Scan
        run: |  # استخدم | للسماح بالكتابة على عدة أسطر
            sonar-scanner
                -Dsonar.host.url=${{ secrets.SONAR_URL }}
                -Dsonar.login=${{ secrets.SONAR_TOKEN }}
                -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
                -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
                -Dsonar.sources=src/
                -Dsonar.junit.reportsPath=target/surefire-reports/ 
                -Dsonar.jacoco.reportsPath=target/jacoco.exec 
                -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
                -Dsonar.java.binaries=target/classes